site_name: Pycht Documentation
site_url: https://tlentali.com
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Reference:
      - Pycht: reference/pycht.md
      - Image Processing: reference/image_processing.md
      - Clustering: reference/clustering.md

cname: tlentali.com
